#ifndef NEWWORLD_STANDARD_LIT_DEPTH_ONLY_PASS_INCLUDED
#define NEWWORLD_STANDARD_LIT_DEPTH_ONLY_PASS_INCLUDED

#include "../../../ShaderLibrary/Passes/DepthOnlyPass.hlsl"

#endif // NEWWORLD_STANDARD_LIT_DEPTH_ONLY_PASS_INCLUDED
