#ifndef NEWWORLD_STANDARD_LIT_SHADOW_CASTER_PASS_INCLUDED
#define NEWWORLD_STANDARD_LIT_SHADOW_CASTER_PASS_INCLUDED

#include "../../../ShaderLibrary/Passes/ShadowCasterPass.hlsl"

#endif // NEWWORLD_STANDARD_LIT_SHADOW_CASTER_PASS_INCLUDED
